name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
    - title: '🚀 New'
      labels:
          - 'feature'
          - 'enhancement'
    - title: '🐛 Fixes'
      labels:
          - 'fix'
          - 'bugfix'
          - '☢️ Bug'
    - title: '🧹 Updates'
      labels:
          - 'fix'
          - 'bugfix'
          - 'bug'
    - title: '📚 Documentation'
      label: '📒 Documentation'
change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
    major:
        labels:
            - 'major'
    minor:
        labels:
            - 'minor'
    patch:
        labels:
            - 'patch'
    default: patch
template: |
    🔥&nbsp;&nbsp;**New**
    - text

    🧹&nbsp;&nbsp;**Updates**
    - text

    🩹&nbsp;&nbsp;**Fixes**
    - text

    📚&nbsp;&nbsp;**Documentation**
    - text

    ## Changes
    $CHANGES

    Thank you $CONTRIBUTORS for making this update possible.
